# Generated by Django 6.0.3 on 2026-03-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='Planned', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('expected_yield', models.FloatField()),
                ('expected_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setup.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_setup.field')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop_season.season')),
            ],
        ),
    ]
